from aicutting.core.models import (
    CutPlan,
    DroneShotType,
    MediaAsset,
    Timeline,
    TimelineClip,
    Transition,
    TransitionType,
)
from aicutting.director.edit_models import (
    EditClip,
    EditDecision,
    FootageMoment,
    MomentRating,
    RhythmSlot,
)

_CALM = {DroneShotType.ESTABLISHING, DroneShotType.TOP_DOWN, DroneShotType.ORBIT}
_ENERGETIC = {DroneShotType.REVEAL, DroneShotType.APPROACH, DroneShotType.FLY_THROUGH}


def fallback_edit(kept: list[MomentRating], slots: list[RhythmSlot]) -> EditDecision:
    pool = sorted(kept, key=lambda rating: rating.cinematic_score, reverse=True)
    used: set[str] = set()
    prev: DroneShotType | None = None
    clips: list[EditClip] = []
    for slot in slots:
        prefer = _ENERGETIC if slot.is_accent else _CALM
        choice = _best(pool, used, prev, prefer)
        if choice is None:
            break
        used.add(choice.moment_id)
        prev = choice.shot_type
        clips.append(
            EditClip(
                slot_index=slot.index,
                moment_id=choice.moment_id,
                effect=_fallback_effect(slot, choice.shot_type),
                reason=f"{choice.shot_type.value} fallback",
            )
        )
    return EditDecision(arc="deterministic fallback", clips=clips)


def _fallback_effect(slot: RhythmSlot, shot_type: DroneShotType) -> TransitionType:
    if slot.is_accent and shot_type in _ENERGETIC:
        return TransitionType.SMOOTH_ZOOM
    if slot.energy <= 0.35 and shot_type in _CALM:
        return TransitionType.DISSOLVE
    return TransitionType.HARD_CUT


def _best(
    pool: list[MomentRating],
    used: set[str],
    prev: DroneShotType | None,
    prefer: set[DroneShotType],
) -> MomentRating | None:
    candidates = [r for r in pool if r.moment_id not in used and r.shot_type != prev]
    if not candidates:
        candidates = [r for r in pool if r.moment_id not in used]
    if not candidates:
        return None
    return max(candidates, key=lambda r: (r.shot_type in prefer, r.cinematic_score))


def assemble_cut_plan(
    edit: EditDecision,
    slots: list[RhythmSlot],
    moments: dict[str, FootageMoment],
    media: list[MediaAsset],
    trim_s: float = 12.0,
) -> CutPlan:
    durations = {asset.path: asset.duration_s for asset in media}
    by_slot = {clip.slot_index: clip for clip in edit.clips}
    base = media[0]
    clips: list[TimelineClip] = []
    cursor = 0.0
    used: set[str] = set()
    prev_effect: TransitionType | None = None
    for slot in slots:
        clip = by_slot.get(slot.index)
        if clip is None or clip.moment_id in used or clip.moment_id not in moments:
            continue
        moment = moments[clip.moment_id]
        window = _clamp_window(
            moment.timestamp_s, slot.duration_s, durations.get(moment.asset_path, 0.0), trim_s
        )
        if window is None:
            continue
        start_s, end_s = window
        effect = clip.effect
        if effect == prev_effect and effect != TransitionType.HARD_CUT:
            effect = TransitionType.HARD_CUT
        clips.append(
            TimelineClip(
                asset_path=moment.asset_path,
                source_start_s=start_s,
                source_end_s=end_s,
                timeline_start_s=round(cursor, 3),
                transition_in=Transition(kind=effect, duration_s=_effect_duration(effect)),
                speed=1.0,
                color_intent="subtle_cinematic",
            )
        )
        used.add(clip.moment_id)
        prev_effect = effect
        cursor = round(cursor + (end_s - start_s), 3)

    target = round(cursor, 3)
    if target <= 0:
        target = slots[-1].end_s if slots else 1.0
    timeline = Timeline(
        target_duration_s=target, clips=clips, fps=base.fps, width=base.width, height=base.height
    )
    return CutPlan(
        target_duration_s=target,
        style="ai_drone_director_30",
        timeline=timeline,
        notes=[f"Generated by AI Drone Director 3.0 ({len(clips)} clips). Arc: {edit.arc}"],
    )


def _clamp_window(
    timestamp_s: float, duration_s: float, file_duration_s: float, trim_s: float
) -> tuple[float, float] | None:
    if file_duration_s <= 0 or duration_s <= 0:
        return None
    low = min(trim_s, file_duration_s * 0.1)
    high = max(low + 0.1, file_duration_s - low)
    start = max(low, timestamp_s - duration_s / 2)
    end = min(high, start + duration_s)
    start = max(low, end - duration_s)
    if end - start < 0.4:
        return None
    return round(start, 3), round(end, 3)


def _effect_duration(effect: TransitionType) -> float:
    if effect == TransitionType.DISSOLVE:
        return 0.35
    if effect in {TransitionType.SMOOTH_ZOOM, TransitionType.WHIP_BLUR}:
        return 0.25
    return 0.0
